version: "2"

networks:
  zeebe_network:

services:
  zeebe:
    container_name: zeebe_broker-operate_broker
    image: camunda/zeebe:latest
    environment:
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_DELAY=5
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1000
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_MEMORYLIMIT=104857600
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_PREFIX=zeebe-record
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_CREATETEMPLATE=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_COMAND=false
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_EVENT=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_REJECTION=false
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_DEPLOYMENT=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_INCIDENT=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_JOB=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_JOBBATCH=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_MESSAGE=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_MESSAGESUBSCRIPTION=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_PROCESSINSTANCE=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_PROCESSINSTANCECREATION=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_PROCESSINSTANCESUBSCRIPTION=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_VARIABLE=true
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_VARIABLEDOCUMENT=true
    ports:
      - "26500:26500"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - zeebe_network
  operate:
    container_name: zeebe_broker-operate_operate
    image: camunda/operate:latest
    environment:
      - CAMUNDA_OPERATE_ELASTICSEARCH_CLUSTERNAME=elasticsearch
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_CLUSTERNAME=elasticsearch
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PREFIX=zeebe-record
      - LOGGING_LEVEL_ROOT=INFO
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    networks:
      - zeebe_network
  elasticsearch:
    container_name: zeebe_broker-operate_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - zeebe_network
  kibana:
    container_name: zeebe_broker-operate_kibana
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - "5601:5601"
    networks:
      - zeebe_network