version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  gateway:
    container_name: zeebe_cluster-s_gateway_0.22.2
    image: camunda/zeebe:0.22.2
    environment:
      - ZEEBE_LOG_LEVEL=info
      - ZEEBE_STANDALONE_GATEWAY=true
      - ZEEBE_GATEWAY_CONTACT_POINT=node0:26502
      - ZEEBE_GATEWAY_CLUSTER_HOST=gateway
      - ZEEBE_GATEWAY_CLUSTER_PORT=26502
    ports:
      - "26500:26500"
    networks:
      - zeebe_network
  node0:
    container_name: zeebe_cluster-s_broker0_0.22.2
    image: camunda/zeebe:0.22.2
    environment:
      - ZEEBE_LOG_LEVEL=info
      - ZEEBE_NODE_ID=0
      - ZEEBE_PARTITIONS_COUNT=2
      - ZEEBE_REPLICATION_FACTOR=3
      - ZEEBE_CLUSTER_SIZE=3
      - ZEEBE_CONTACT_POINTS=node0:26502
    ports:
      - "26600:26500"
    networks:
      - zeebe_network
  node1:
    container_name: zeebe_cluster-s_broker1_0.22.2
    image: camunda/zeebe:0.22.2
    environment:
      - ZEEBE_LOG_LEVEL=info
      - ZEEBE_NODE_ID=1
      - ZEEBE_PARTITIONS_COUNT=2
      - ZEEBE_REPLICATION_FACTOR=3
      - ZEEBE_CLUSTER_SIZE=3
      - ZEEBE_CONTACT_POINTS=node0:26502
    networks:
      - zeebe_network
    depends_on:
      - node0
  node2:
    container_name: zeebe_cluster-s_broker2_0.22.2
    image: camunda/zeebe:0.22.2
    environment:
      - ZEEBE_LOG_LEVEL=info
      - ZEEBE_NODE_ID=2
      - ZEEBE_PARTITIONS_COUNT=2
      - ZEEBE_REPLICATION_FACTOR=3
      - ZEEBE_CLUSTER_SIZE=3
      - ZEEBE_CONTACT_POINTS=node0:26502
    networks:
      - zeebe_network
    depends_on:
      - node1
